package com.restaurant.ai.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA Entity mapped to the 'predictions' table.
 * Stores demand forecasting results generated by the XGBoost ML model.
 */
@Entity
@Table(name = "predictions", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"menu_item_id", "prediction_date", "model_name"})
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DemandPrediction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "menu_item_id", nullable = false)
    private MenuItem menuItem;

    @Column(name = "prediction_date", nullable = false)
    private LocalDate predictionDate;

    @Column(name = "predicted_quantity", nullable = false, precision = 10, scale = 2)
    private BigDecimal predictedQuantity;

    @Column(name = "confidence_lower", precision = 10, scale = 2)
    private BigDecimal confidenceLower;

    @Column(name = "confidence_upper", precision = 10, scale = 2)
    private BigDecimal confidenceUpper;

    @Column(name = "model_name", length = 50)
    private String modelName;

    @Column(name = "model_version", length = 20)
    private String modelVersion;

    @Column(name = "is_festival_day")
    private Boolean isFestivalDay = false;

    @Column(name = "actual_quantity", precision = 10, scale = 2)
    private BigDecimal actualQuantity;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
