package com.restaurant.ai.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA Entity mapped to the 'inventory_predictions' table.
 * Stores waste optimization results generated by the RandomForest ML model.
 */
@Entity
@Table(name = "inventory_predictions", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"inventory_item_name", "prediction_date", "model_name"})
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class InventoryPrediction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "inventory_item_name", nullable = false, length = 100)
    private String inventoryItemName;

    @Column(name = "prediction_date", nullable = false)
    private LocalDate predictionDate;

    @Column(name = "current_stock", precision = 10, scale = 2)
    private BigDecimal currentStock;

    @Column(name = "daily_usage", precision = 10, scale = 2)
    private BigDecimal dailyUsage;

    @Column(name = "predicted_waste_percentage", nullable = false, precision = 5, scale = 2)
    private BigDecimal predictedWastePercentage;

    @Column(name = "action_recommended", length = 100)
    private String actionRecommended;

    @Column(name = "model_name", length = 50)
    private String modelName = "RandomForest";

    @Column(name = "model_version", length = 20)
    private String modelVersion;

    @Column(name = "actual_waste_percentage", precision = 5, scale = 2)
    private BigDecimal actualWastePercentage;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
